import type { NetworkMember } from "@/lib/types";

export interface FlowPolicy {
  layer2Only: boolean;
  restrict: boolean;
  services: string[];
  exemptMembers: string[];
  custom: Array<{
    name: string;
    protocol: "tcp" | "udp" | "both";
    port: string;
  }>;
}

export interface Metadata {
  description: string;
  rulesSource: string;
  templatePolicy: FlowPolicy | null;
}

export interface MemberDraft extends NetworkMember {
  description: string;
  capabilitiesJson: string;
  tagsJson: string;
}

export const defaultPolicy: FlowPolicy = {
  layer2Only: false,
  restrict: false,
  services: [],
  exemptMembers: [],
  custom: [],
};

export const serviceOptions = [
  ["ping", "Ping & traceroute", "ICMP and ICMPv6"],
  ["dns", "DNS", "53/UDP and 53/TCP"],
  ["http", "HTTP", "80/TCP"],
  ["https", "HTTPS", "443/TCP"],
  ["ssh", "SSH", "22/TCP"],
  ["rdp", "Remote Desktop", "3389/TCP"],
  ["smb", "Windows file sharing", "137–138/UDP, 139 and 445/TCP"],
] as const;

export const ruleStarters = {
  "Allow all": "# Permit all network traffic\naccept;",
  "Layer 2 filter":
    "# Permit IPv4, IPv6 and ARP only\ndrop not ethertype ipv4 and not ethertype ipv6 and not ethertype arp;\naccept;",
  "SSH + web":
    "accept ipprotocol tcp and chr tcp_ack;\naccept ipprotocol tcp and dport 22;\naccept ipprotocol tcp and dport 80;\naccept ipprotocol tcp and dport 443;\ndrop;",
  "Client isolation":
    "# Replace the node ID with your gateway/server\naccept ztsrc 0123456789;\naccept ztdest 0123456789;\ndrop;",
};

export function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value));
}

export function dateTimeInput(value: unknown) {
  const timestamp = Number(value || 0);
  if (!timestamp) return "";
  const date = new Date(timestamp);
  const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000);
  return local.toISOString().slice(0, 16);
}

export function emptyMember(): MemberDraft {
  return {
    id: "",
    name: "",
    authorized: false,
    activeBridge: false,
    noAutoAssignIps: false,
    ssoExempt: false,
    ipAssignments: [],
    description: "",
    capabilitiesJson: "[]",
    tagsJson: "[]",
  };
}

export function memberDraftFrom(member: NetworkMember): MemberDraft {
  return {
    ...emptyMember(),
    ...member,
    description: String(member.description || ""),
    capabilitiesJson: JSON.stringify(member.capabilities || [], null, 2),
    tagsJson: JSON.stringify(member.tags || [], null, 2),
  };
}

export function generatedSubnet() {
  const bytes = crypto.getRandomValues(new Uint8Array(2));
  const second = 16 + (bytes[0] % 224);
  const third = 1 + (bytes[1] % 253);
  return {
    route: `10.${second}.${third}.0/24`,
    start: `10.${second}.${third}.1`,
    end: `10.${second}.${third}.254`,
  };
}

export function generateFlowSource(policy: FlowPolicy) {
  const lines = [
    "# Generated by ZT Control Plane",
    "# Rules are distributed and stateless.",
    "",
  ];
  if (policy.layer2Only)
    lines.push(
      "drop not ethertype ipv4 and not ethertype ipv6 and not ethertype arp;",
      "",
    );
  for (const id of policy.exemptMembers)
    lines.push(`accept ztsrc ${id};`, `accept ztdest ${id};`);
  if (policy.exemptMembers.length) lines.push("");
  if (!policy.restrict) {
    lines.push("accept;");
    return lines.join("\n");
  }
  lines.push("accept ethertype arp;");
  if (policy.services.includes("ping"))
    lines.push("accept ipprotocol icmp;", "accept ipprotocol icmp6;");
  if (
    policy.services.some((service) =>
      ["dns", "http", "https", "ssh", "rdp", "smb"].includes(service),
    ) ||
    policy.custom.some((item) => item.protocol !== "udp")
  )
    lines.push("accept ipprotocol tcp and chr tcp_ack;");
  if (policy.services.includes("dns"))
    lines.push(
      "accept ipprotocol udp and dport 53;",
      "accept ipprotocol udp and sport 53;",
      "accept ipprotocol tcp and dport 53;",
    );
  for (const [service, port] of [
    ["http", "80"],
    ["https", "443"],
    ["ssh", "22"],
    ["rdp", "3389"],
  ])
    if (policy.services.includes(service))
      lines.push(`accept ipprotocol tcp and dport ${port};`);
  if (policy.services.includes("smb"))
    lines.push(
      "accept ipprotocol udp and dport 137-138;",
      "accept ipprotocol tcp and dport 139;",
      "accept ipprotocol tcp and dport 445;",
    );
  for (const custom of policy.custom) {
    if (!custom.port.trim()) continue;
    if (custom.protocol !== "udp")
      lines.push(`accept ipprotocol tcp and dport ${custom.port.trim()};`);
    if (custom.protocol !== "tcp")
      lines.push(`accept ipprotocol udp and dport ${custom.port.trim()};`);
  }
  lines.push("drop;");
  return lines.join("\n");
}
