blank_issues_enabled: false
contact_links:
  - name: ZeroTier product support
    url: https://www.zerotier.com/contact/
    about: This community project cannot provide support for ZeroTier products or accounts.
